const UsagePage = () => {
	return (
		<div>
      <div className="flex flex-col justify-center items-start space-y-2 mb-2">
        <h2 className="text-2xl-600 text-primary">Credit Uage</h2>
        <p className="text-xl-400 text-black">Credits are used for each message generated by sorayia</p>
      </div>
		</div>
	)
}

export default UsagePage